

import '../themes/color.dart';

const List exploreForyou = [
  {
    "hasImageUrl": true,
    "imageUrl": "https://images.unsplash.com/photo-1534972195531-d756b9bfa9f2?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTF8fGNvZGV8ZW58MHx8MHx8&auto=format&fit=crop&w=800&q=60",
    "profileUrl": "https://images.unsplash.com/photo-1531427186611-ecfd6d936c79?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8cHJvZmlsZXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=800&q=60",
    "profileName": "awesome",
    "profileUsername": "sindresorhus",
    "description": "😎 Awesome lists about all kinds of\n interesting topics",
    "star": "201.7k",
    "contributor": "521",
    "hasLanguage": false,
    "colorIconLanguage": blue,
    "language": "",
  },
  {
    "hasImageUrl": false,
    "imageUrl": "",
    "profileUrl": "https://images.unsplash.com/photo-1457449940276-e8deed18bfff?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Nnx8cHJvZmlsZXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=800&q=60",
    "profileName": "awesome-python",
    "profileUsername": "vinta",
    "description": "A curated list of awesome Python frameworks, libraries, software and resources",
    "star": "127.4k",
    "contributor": "393",
    "hasLanguage": true,
    "colorIconLanguage": blue,
    "language": "Python",
  },
  {
    "hasImageUrl": true,
    "imageUrl": "https://images.unsplash.com/photo-1602992708529-c9fdb12905c9?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTZ8fGNvZGV8ZW58MHx8MHx8&auto=format&fit=crop&w=800&q=60",
    "profileUrl": "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTh8fHByb2ZpbGV8ZW58MHx8MHx8&auto=format&fit=crop&w=800&q=60",
    "profileName": "awesome-selfhosted",
    "profileUsername": "awesome-selfhosted",
    "description": "A list of Free Software network services and web applications which can be hosted on your own servers",
    "star": "88.6k",
    "contributor": "1045",
    "hasLanguage": true,
    "colorIconLanguage": yellow,
    "language": "JavaScript",
  },
  {
    "hasImageUrl": false,
    "imageUrl": "",
    "profileUrl": "https://images.unsplash.com/photo-1531891437562-4301cf35b7e4?crop=entropy&cs=tinysrgb&fm=jpg&ixlib=rb-1.2.1&q=60&raw_url=true&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mzl8fHByb2ZpbGV8ZW58MHx8MHx8&auto=format&fit=crop&w=800",
    "profileName": "awesome-go",
    "profileUsername": "avelino",
    "description": "A curated list of awesome Go frameworks, libraries, software and resources",
    "star": "80.7k",
    "contributor": "1591",
    "hasLanguage": true,
    "colorIconLanguage": blue,
    "language": "Go",
  },
  {
    "hasImageUrl": false,
    "imageUrl": "",
    "profileUrl": "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NDJ8fHByb2ZpbGV8ZW58MHx8MHx8&auto=format&fit=crop&w=800&q=60",
    "profileName": "the-book-of-secret-knowledge",
    "profileUsername": "trimstray",
    "description": "A collection of inspiring lists, manuals, cheatsheets, blogs, hacks, one-liners, cli/web tools and more",
    "star": "68.1k",
    "contributor": "101",
    "hasLanguage": false,
    "colorIconLanguage": blue,
    "language": "Python",
  },
];

const List exploreTrending = [
  {
    "hasImageUrl": true,
    "imageUrl": "https://events-feed.github.com/events/futurestack-2022/FutureStack.jpeg",
    "profileUrl": "https://github.githubassets.com/images/email/explore/explore-gradient-icon.png",
    "profileName": "{Future} Stack 2022",
    "profileUsername": "future-stack",
    "description": "It’s the ultimate software engineering conference.Get deep into what your peers are doing.",
    "star": "120 today",
    "contributor": "48",
    "hasLanguage": false,
    "colorIconLanguage": red,
    "language": "Swift",
  },
  {
    "hasImageUrl": true,
    "imageUrl": "https://images.unsplash.com/photo-1595675024853-0f3ec9098ac7?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8dGVjaG9sb2d5fGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=800&q=60",
    "profileUrl": "https://images.unsplash.com/photo-1595675024853-0f3ec9098ac7?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8dGVjaG9sb2d5fGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=800&q=60",
    "profileName": "CodeEditor",
    "profileUsername": "CodeEditApp",
    "description": "CodeEditor is a free, open-source, cross-platform code editor for macOS, Windows, and Linux. It’s a powerful, easy-to-use, and easy-to-customize code editor that’s easy to use and easy to learn.",
    "star": "120 today",
    "contributor": "48",
    "hasLanguage": true,
    "colorIconLanguage": red,
    "language": "Swift",
  },
  {
    "hasImageUrl": true,
    "imageUrl": "https://events-feed.github.com/events/NdcMelbourne2022/ndcmelbourne.jpeg",
    "profileUrl": "https://events-feed.github.com/events/NdcMelbourne2022/ndcmelbourne.jpeg",
    "profileName": "End-to-end DevOps with GitHub",
    "profileUsername": "end-to-end-devops",
    "description": "GitHub is more than just a place to keep your code. GitHub offers features that cover your whole DevOps lifecycle from idea all the way into production",
    "star": "90 today",
    "contributor": "403",
    "hasLanguage": false,
    "colorIconLanguage": red,
    "language": "Swift",
  },
  {
    "hasImageUrl": true,
    "imageUrl": "https://marketplace-screenshots.githubusercontent.com/1469/a19f9a00-b456-11ea-902a-1ece7cefbd78",
    "profileUrl": "https://avatars.githubusercontent.com/ml/1469?s=400&v=4",
    "profileName": "GitKraken Boards",
    "profileUsername": "GitKraken Boards",
    "description": "GitKraken Boards syncs in real-time with GitHub Issues and GitHub Milestones so changes made in either system are immediately reflected in the other.",
    "star": "12k",
    "contributor": "129",
    "hasLanguage": false,
    "colorIconLanguage": blue,
    "language": "",
  },
];